"use strict";
exports.__esModule = true;
var pokebag_1 = require("./pokebag");
var pikachu_1 = require("./pikachu");
var charmander_1 = require("./charmander");
var pika = new pikachu_1.Pikachu("Pikachu", 60, [{ 'move': 'Electric Ring', 'damage': 50 }, { 'move': 'Pika Punch', 'damage': 20 }]);
var char = new charmander_1.Charmander("Charmander", 60, [{ 'move': 'Head Butt', 'damage': 10 }, { 'move': 'Flare', 'damage': 30 }]);
var bag = new pokebag_1.PokeBag(10);
pika.attack(char, 'Electric Ring');
char.attack(pika, 'Flare');
bag.addToBag(pika);
bag.addToBag(char);
bag.removeFromBag(char);
bag.getAllInBag();
