"use strict";
exports.__esModule = true;
var pokebag_1 = require("./pokebag");
var pikachu_1 = require("./pikachu");
var charmander_1 = require("./charmander");
var pokemon_1 = require("./pokemon");
pokemon_1.Pokemon.getPopulation();
var pika = new pikachu_1.Pikachu("Pikachu", 60);
var char = new charmander_1.Charmander("Charmander", 60);
pokemon_1.Pokemon.getPopulation();
pokemon_1.Pokemon.getPopulationHealth();
var bag = new pokebag_1.PokeBag(10);
pika.attack(char, 'Electric Ring');
char.attack(pika, 'Flare');
bag.addToBag(pika);
bag.addToBag(char);
bag.removeFromBag(char);
bag.getAllInBag();
